name: AWS Setup

on:
  workflow_call:

jobs:
  configure_aws:
    name: configure aws
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Configure AWS cred
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: "ap-south-1"