name: Github Actions Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  configure-aws:
    uses: ./.github/workflows/aws.yml
    secrets: inherit

  job1:
    name: Job1
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0

      - name: Configure AWS Credentials
        needs: configure-aws

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

